import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import CustomInputNumber from '@/component/CustomInputNumber/CustomInputNumber';
import { useState } from 'react';
import RoomAllocation from '@/component/RoomAllocation/RoomAllocation';

const inter = Inter({ subsets: ['latin'] });

export interface I_Guset {
  adult: number;
  child: number;
}

export interface I_Rooms {
  roomPrice: number;
  adultPrice: number;
  childPrice: number;
  capacity: number;
}

export default function Home() {
  // const guest = { adult: 4, child: 2 };
  // const rooms = [
  //   { roomPrice: 1000, adultPrice: 200, childPrice: 100, capacity: 4 },
  //   { roomPrice: 0, adultPrice: 500, childPrice: 500, capacity: 4 },
  // ];

  const guest = { adult: 7, child: 3 };
  const rooms = [
    { roomPrice: 2000, adultPrice: 200, childPrice: 100, capacity: 4 },
    { roomPrice: 2000, adultPrice: 200, childPrice: 100, capacity: 4 },
    { roomPrice: 2000, adultPrice: 400, childPrice: 200, capacity: 2 },
    { roomPrice: 2000, adultPrice: 400, childPrice: 200, capacity: 2 },
  ];

  // const guest = { adult: 16, child: 0 };
  // const rooms = [
  //   { roomPrice: 500, adultPrice: 500, childPrice: 300, capacity: 4 },
  //   { roomPrice: 500, adultPrice: 500, childPrice: 300, capacity: 4 },
  //   { roomPrice: 0, adultPrice: 500, childPrice: 300, capacity: 8 },
  //   { roomPrice: 500, adultPrice: 1000, childPrice: 600, capacity: 2 },
  // ];

  return (
    <>
      <Head>
        <title>Pre Test</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <RoomAllocation
          guest={guest}
          rooms={rooms}
          onChange={(result) => console.log('result', result)}
        />
      </main>
    </>
  );
}
